name: CI

on:
  workflow_call:
    inputs:
      event_name:
        required: true
        type: string
      repo_full_name:
        required: true
        type: string
  push:
    branches:
      - '**'
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  luacheck:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name

    steps:
      - name: Checkout project
        uses: actions/checkout@v6.0.3

      - name: Run Luacheck
        uses: nebularg/actions-luacheck@v1.1.2
        with:
          args: -q

  unit-tests:
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name
    env:
      TZ: Europe/Berlin

    steps:
      - name: Checkout project
        uses: actions/checkout@v6.0.3

      - name: Install Lua
        uses: leafo/gh-actions-lua@v13.0.0
        with:
          luaVersion: "5.1"

      - name: Install luarocks packages
        uses: leafo/gh-actions-luarocks@v6.1.0
        with:
          luaRocksVersion: "3.13.0"

      - name: Install test dependencies
        run: |
          luarocks install busted 2.2.0-1

      - name: Run busted Unit Tests
        run: busted -p ".test.lua" .
